version: '3'
services:
  loadbalancer:
    command: sh -c "uvicorn app.main:app --reload --host 0.0.0.0"
    build:
        context: ./loadbalancer
        dockerfile: Dockerfile
    ports:
      - 8001:8000
    volumes:
      - ./loadbalancer:/loadbalancer
  celery:
    command: sh -c "celery -A app.config.celery_app worker -l info"
    build:
        context: ./loadbalancer
        dockerfile: Dockerfile
    volumes:
      - ./loadbalancer:/loadbalancer
    environment:
      BROKER_URL: 'redis://redis:6379'
    depends_on:
      - redis
  redis:
    image: redis:6.2.1-alpine
  glot:
    restart: always
    image: glot/docker-run:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8088:8088
    environment:
      API_ACCESS_TOKEN: token
      DOCKER_CONTAINER_ULIMIT_NPROC_SOFT: 2000
      DOCKER_CONTAINER_ULIMIT_NPROC_HARD: 5000
