version: '3.8'

x-service-basic: &service-basic
  volumes:
    - ./loadbalancer:/loadbalancer
  environment:
    BROKER_URL: 'redis://redis:6379'

services:
  loadbalancer:
    command: sh -c 'uvicorn app.main:app --reload --host 0.0.0.0'
    build:
        context: ./loadbalancer
        dockerfile: Dockerfile
    ports:
      - 8001:8000
    <<: *service-basic

  celery:
    command: sh -c 'celery -A app.config.celery_app worker --loglevel=INFO -c 4'
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    depends_on:
      - redis
    <<: *service-basic

  redis:
    image: redis:6.2.1-alpine

  glot:
    image: glot/docker-run:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8088:8088
    environment:
      API_ACCESS_TOKEN: token
      DOCKER_CONTAINER_ULIMIT_NPROC_SOFT: 2000
      DOCKER_CONTAINER_ULIMIT_NPROC_HARD: 5000

  flower:
    image: mher/flower
    volumes:
    - ./loadbalancer:/loadbalancer
    environment:
      CELERY_BROKER_URL: 'redis://redis:6379'
      FLOWER_PORT: 5555
    ports:
      - 5555:5555
    depends_on:
      - redis
