name: Publish to Docker Hub
on:
  release:
    types: [published]
jobs:
  build-load-push-images:
    name: Build, Load images and Push them to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: |
          echo "Install KVM"
          sudo apt-get install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils

          echo "Get privileges for build_all.sh script"
          cd ./images
          chmod +x ./scripts/build_all.sh

          echo "Login to Docker"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          echo "Build all images"
          ./scripts/build_all.sh

          echo "Load images"
          docker load ./built/python
          docker load ./built/js

          echo "Push to Docker Hub"
          docker push raisultan/python:latest
          docker push raisultan/js:latest

          echo "Done!"
