name: Publish to Docker Hub
on:
  release:
    types: [published]
jobs:
  build-load-push-images:
    name: Build, Load images and Push them to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            system-features = kvm
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: |
          echo "Get privileges for build_all.sh script"
          cd ./coderunner/images
          chmod +x ./scripts/build_all.sh

          echo "Build all images"
          ./scripts/build_all.sh

          echo "Load images"
          docker load < ./built/python
          docker load < ./built/js

          echo "Push to Docker Hub"
          docker push raisultan/python:latest
          docker push raisultan/js:latest

          echo "Done!"
